apiVersion: v1
kind: ServiceAccount
metadata:
  name: student
  namespace: anyops-rbac
  labels:
    name: student
secrets:
  - name: student-secret

---

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: student-secret
  namespace: anyops-rbac
  annotations:
    kubernetes.io/service-account.name: "student"
  labels:
    name: student

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: anyops-rbac
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
