name: victoria-logs-standalone

services:
  victoria-logs:
    image: docker.io/victoriametrics/victoria-logs:v1.53.0
    command:
      - -storageDataPath=/victoria-logs-data
    ports:
      - 127.0.0.1:9428:9428
    volumes:
      - victoria_logs_data:/victoria-logs-data
    restart: unless-stopped

volumes:
  victoria_logs_data:
